/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polinomio;

/**
 *
 * @author manuel
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioPolinomio = new javax.swing.ButtonGroup();
        contenedor = new javax.swing.JPanel();
        polinomios = new javax.swing.JPanel();
        labelCoeficiente = new javax.swing.JLabel();
        coeficiente = new javax.swing.JTextField();
        labelExponente = new javax.swing.JLabel();
        exponente = new javax.swing.JTextField();
        px = new javax.swing.JRadioButton();
        qx = new javax.swing.JRadioButton();
        insertarTermino = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaPolinomios = new javax.swing.JTextArea();
        verPolinomios = new javax.swing.JButton();
        operaciones = new javax.swing.JPanel();
        suma = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        division = new javax.swing.JButton();
        evaluacion = new javax.swing.JButton();
        derivacion = new javax.swing.JButton();
        labelK = new javax.swing.JLabel();
        k = new javax.swing.JTextField();
        labelN = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TAD POLINOMIO P(x)");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        contenedor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Simulación de Operaciones Básicas con Polinomios ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Ubuntu", 1, 16))); // NOI18N
        contenedor.setName("contenedor"); // NOI18N

        polinomios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Construcción de Polinomios P(x) y Q(x)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Ubuntu", 1, 14))); // NOI18N
        polinomios.setName("polinomios"); // NOI18N

        labelCoeficiente.setText("Coeficiente:");

        labelExponente.setText("Exponente:");

        radioPolinomio.add(px);
        px.setSelected(true);
        px.setText("P(x)");
        px.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pxActionPerformed(evt);
            }
        });

        radioPolinomio.add(qx);
        qx.setText("Q(x)");

        insertarTermino.setText("Insertar Termino");
        insertarTermino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarTerminoActionPerformed(evt);
            }
        });

        areaPolinomios.setColumns(20);
        areaPolinomios.setRows(5);
        jScrollPane1.setViewportView(areaPolinomios);

        verPolinomios.setText("Ver Polinomios");
        verPolinomios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPolinomiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout polinomiosLayout = new javax.swing.GroupLayout(polinomios);
        polinomios.setLayout(polinomiosLayout);
        polinomiosLayout.setHorizontalGroup(
            polinomiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(polinomiosLayout.createSequentialGroup()
                .addGroup(polinomiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(polinomiosLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(polinomiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCoeficiente)
                            .addGroup(polinomiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(px)
                                .addComponent(labelExponente)))
                        .addGap(18, 18, 18)
                        .addGroup(polinomiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(coeficiente, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(exponente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, polinomiosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(qx)
                        .addGap(33, 33, 33)))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(polinomiosLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(insertarTermino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(verPolinomios)
                .addGap(181, 181, 181))
        );
        polinomiosLayout.setVerticalGroup(
            polinomiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(polinomiosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(polinomiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(polinomiosLayout.createSequentialGroup()
                        .addGroup(polinomiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCoeficiente)
                            .addComponent(coeficiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(polinomiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelExponente)
                            .addComponent(exponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(polinomiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(px)
                            .addComponent(qx)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(polinomiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertarTermino)
                    .addComponent(verPolinomios))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        operaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operaciones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Ubuntu", 1, 14))); // NOI18N
        operaciones.setName("operaciones"); // NOI18N

        suma.setText("Suma: P(x) +Q(x)");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        resta.setText("Resta: P(x) - Q(x)");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        multiplicacion.setText("Multiplicación: P(x) * Q(x)");

        division.setText("División: P(x) / Q(x)");

        evaluacion.setText("Evaluar P(x) en n");

        derivacion.setText("Derivar P(x)");

        labelK.setText("Ingrese k:");

        labelN.setText("Ingrese n:");

        areaResultado.setColumns(20);
        areaResultado.setRows(5);
        jScrollPane2.setViewportView(areaResultado);

        javax.swing.GroupLayout operacionesLayout = new javax.swing.GroupLayout(operaciones);
        operaciones.setLayout(operacionesLayout);
        operacionesLayout.setHorizontalGroup(
            operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operacionesLayout.createSequentialGroup()
                .addGroup(operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(operacionesLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suma)
                            .addComponent(division)))
                    .addGroup(operacionesLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelK)
                            .addComponent(labelN)
                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(operacionesLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resta)
                            .addComponent(evaluacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(multiplicacion)
                            .addComponent(derivacion))
                        .addGap(82, 82, 82))
                    .addGroup(operacionesLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        operacionesLayout.setVerticalGroup(
            operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suma)
                    .addComponent(resta)
                    .addComponent(multiplicacion))
                .addGap(24, 24, 24)
                .addGroup(operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(division)
                    .addComponent(evaluacion)
                    .addComponent(derivacion))
                .addGap(29, 29, 29)
                .addGroup(operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(operacionesLayout.createSequentialGroup()
                        .addComponent(labelK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(operaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(polinomios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(polinomios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pxActionPerformed

    private void verPolinomiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPolinomiosActionPerformed
        
        String polinomios = "P(x) = ";
        polinomios += Polinomio.p.mostrarPolinomio() + "\n";
        polinomios += "Q(x) = ";
        polinomios += Polinomio.q.mostrarPolinomio() + "\n";
        
        areaPolinomios.setText(polinomios);
        
    }//GEN-LAST:event_verPolinomiosActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        // TODO add your handling code here:
         Polinomio.s = Lista.unir(Polinomio.p, Polinomio.q); // Creamos un polinomio con la suma de ambos
         
         Polinomio.sum = Lista.simplifica(Polinomio.s); // Simpflicamos el polinomio obtenido
         
         areaResultado.setText(Polinomio.sum.mostrarPolinomio()); // Mostramos el polinomio
        
    }//GEN-LAST:event_sumaActionPerformed

    private void insertarTerminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarTerminoActionPerformed
        
        if(!coeficiente.getText().equals("") && !exponente.getText().equals("")) { // Si tienen datos los camposs
            
            int c = Integer.parseInt(coeficiente.getText()); // Convertimos el texto del JTextField a entero
            int e = Integer.parseInt(exponente.getText()); // Convertimos el texto del JTextField a entero
           
            if(px.isSelected()) { // Si P(x) esta seleccionada
                
                Polinomio.p.insertarTermino(new Termino(c, e));
            
            } else { // Si Q(x) esta seleccionada
                Polinomio.q.insertarTermino(new Termino(c, e));
            }
        }
    }//GEN-LAST:event_insertarTerminoActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        // TODO add your handling code here:
        
        Polinomio.qNeg = Lista.negativo(Polinomio.q); // Negativo del polinomio q
        
        Polinomio.r = Lista.unir(Polinomio.p, Polinomio.qNeg); // Creamos un polinomio con la suma de ambos P(x) + -Q(x) = P(x) - Q(x)
        
        Polinomio.res = Lista.simplifica(Polinomio.r); // Simplificamos el polinomio
        
        areaResultado.setText(Polinomio.res.mostrarPolinomio()); // Mostramos el polinomio
    }//GEN-LAST:event_restaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaPolinomios;
    private javax.swing.JTextArea areaResultado;
    private javax.swing.JTextField coeficiente;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton derivacion;
    private javax.swing.JButton division;
    private javax.swing.JButton evaluacion;
    private javax.swing.JTextField exponente;
    private javax.swing.JButton insertarTermino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField k;
    private javax.swing.JLabel labelCoeficiente;
    private javax.swing.JLabel labelExponente;
    private javax.swing.JLabel labelK;
    private javax.swing.JLabel labelN;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JTextField n;
    private javax.swing.JPanel operaciones;
    private javax.swing.JPanel polinomios;
    private javax.swing.JRadioButton px;
    private javax.swing.JRadioButton qx;
    private javax.swing.ButtonGroup radioPolinomio;
    private javax.swing.JButton resta;
    private javax.swing.JButton suma;
    private javax.swing.JButton verPolinomios;
    // End of variables declaration//GEN-END:variables

}
